// Central configuration. Swap the basemap source here without touching the app.

export type BasemapSource = "openfreemap" | "pmtiles";

export const config = {
  // --- Basemap -------------------------------------------------------------
  // "openfreemap": hosted vector tiles, zero bundle (default).
  // "pmtiles":     self-hosted single file at pmtilesUrl (100% static).
  // Both use the OpenMapTiles schema, so the custom style in map/style.ts works
  // for either — switching is just changing this one value (and providing the
  // .pmtiles file for the self-hosted option).
  basemapSource: "openfreemap" as BasemapSource,

  openfreemap: {
    tilesUrl: "https://tiles.openfreemap.org/planet", // TileJSON (OpenMapTiles)
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  },
  pmtiles: {
    // Relative to the deployed base path; produced by an offline extract.
    url: `${import.meta.env.BASE_URL}basemap/sydney.pmtiles`,
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  },

  // --- Initial view --------------------------------------------------------
  // Camperdown/Darlington campus.
  center: [151.1875, -33.8883] as [number, number],
  zoom: 15.2,
  minZoom: 9,
  maxZoom: 19,
  // Bounds wide enough to keep the off-campus sites (RNS −33.82, ATP −33.90,
  // Narrabri −30.35) reachable. Format is [SW=[west,south], NE=[east,north]];
  // south must be the more-negative latitude.
  maxBounds: [
    [148.5, -34.6],
    [152.9, -29.4],
  ] as [[number, number], [number, number]],

  // --- Data (generated by scripts/build-data.mjs) --------------------------
  data: {
    tss: `${import.meta.env.BASE_URL}data/facilities.tss.geojson`,
    crf: `${import.meta.env.BASE_URL}data/facilities.crf.geojson`,
    legend: `${import.meta.env.BASE_URL}data/legend.json`,
    footprints: `${import.meta.env.BASE_URL}data/facility-footprints.geojson`,
  },

  attribution:
    '© <a href="https://openfreemap.org" target="_blank" rel="noopener">OpenFreeMap</a> ' +
    '© <a href="https://www.openmaptiles.org/" target="_blank" rel="noopener">OpenMapTiles</a> ' +
    '© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>',
};

export type DetailLevel = "low" | "medium" | "high";
